; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c6-devkitm-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
upload_speed = 115200
upload_flags = 
    --no-stub
    --before=default_reset
    --after=hard_reset
board_build.partitions = default.csv
board_build.filesystem = littlefs
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.0  ; Essencial para formatar dados para a AWS
    knolleary/PubSubClient @ ^2.8    ; Protocolo MQTT
    https://github.com/tzapu/WiFiManager.git
